sidekiqs:
  - 
    name: prolinked-prd
    redis:
      url: redis://127.0.0.1:6379/0
      namespace: prolinkedcare
  - 
    name: mylinkedcare-prd
    redis: 
      url: redis://127.0.0.1:6379/1
      namespace: mylinkedcare